version: '3.4'

services:
  plexrequestsapi:
    image: plexrequestsapi
    build:
      context: .
    ports:
      - 8080:80
    container_name: plexrequestsapi
    environment:
      - ASPNETCORE_ENVIRONMENT
      - AuthenticationSettings__SecretKey
      - TheMovieDbSettings__ApiKey
      - DatabaseSettings__Server
      - DatabaseSettings__Port
      - DatabaseSettings__Database
      - DatabaseSettings__User
      - DatabaseSettings__Password

  mongo:
    image: mongo:latest
    container_name: plexrequestsmongo
    hostname: plexrequestsmongo
    ports:
      - 32770:27017
    environment:
      - MONGO_INITDB_DATABASE
      - MONGO_INITDB_ROOT_USERNAME
      - MONGO_INITDB_ROOT_PASSWORD
