apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.kube.dbAppName }}
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.kube.dbAppName }}
  template:
    metadata:
      labels:
        app: {{ .Values.kube.dbAppName }}
    spec:
      containers:
        - name: {{ .Values.kube.dbAppName }}
          image: {{ .Values.docker.dbImage }}:{{ .Values.docker.dbImageTag }}
          imagePullPolicy: {{ .Values.kube.imagePullPolicy }}
          ports:
            - containerPort: {{ .Values.db.port }}
          env:
            - name: MONGO_INITDB_DATABASE
              valueFrom:
                secretKeyRef:
                  key: mongoDatabase
                  name: plexdb-secrets
            - name: MONGO_INITDB_ROOT_USERNAME
              valueFrom:
                secretKeyRef:
                  key: mongoUsername
                  name: plexdb-secrets
            - name: MONGO_INITDB_ROOT_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: mongoPassword
                  name: plexdb-secrets
